
(() => {
  'use strict';
  const page=document.getElementById('cloudflare-deployment');if(!page)return;
  if(typeof pageNames!=='undefined')pageNames['cloudflare-deployment']=['Cloudflare Deployment','System / Production Delivery'];
  const PAGES=[['brief','Deployment Brief'],['manifest','Package Manifest'],['workflow','GitHub Workflow'],['evidence','Cloudflare Evidence'],['verification','Live Verification'],['record','Deployment Record']];
  const MANIFEST=[{"path": "404.html", "bytes": 523673}, {"path": "_headers", "bytes": 184}, {"path": "assets/css/ekh-os-authenticated-runtime.v1.36.1.css", "bytes": 17113}, {"path": "assets/css/ekh-os-browser-mobile-testing.v1.36.1.css", "bytes": 12523}, {"path": "assets/css/ekh-os-navigation-audit.v1.36.1.css", "bytes": 19231}, {"path": "assets/css/ekh-os-preview.v1.36.1.css", "bytes": 772281}, {"path": "assets/css/ekh-os-security-rls.v1.36.1.css", "bytes": 15193}, {"path": "assets/css/ekh-os.v1.36.1.css", "bytes": 771888}, {"path": "assets/js/ekh-os-authenticated-runtime.v1.36.1.js", "bytes": 24339}, {"path": "assets/js/ekh-os-browser-mobile-testing.v1.36.1.js", "bytes": 10683}, {"path": "assets/js/ekh-os-core.v1.36.1.js", "bytes": 29603}, {"path": "assets/js/ekh-os-features-preview.v1.36.1.js", "bytes": 423675}, {"path": "assets/js/ekh-os-features.v1.36.1.js", "bytes": 422465}, {"path": "assets/js/ekh-os-microcopy.v1.36.1.js", "bytes": 15826}, {"path": "assets/js/ekh-os-navigation-audit.v1.36.1.js", "bytes": 23571}, {"path": "assets/js/ekh-os-security-rls.v1.36.1.js", "bytes": 19020}, {"path": "ekh-os-config.js", "bytes": 183}, {"path": "index.html", "bytes": 523673}];
  const EVIDENCE_KEY='ekh_cf360_evidence_v1360';const RECORD_KEY='ekh_cf360_record_v1360';
  let index=0,startX=null,evidence=load(EVIDENCE_KEY)||null;
  const one=s=>page.querySelector(s),all=s=>[...page.querySelectorAll(s)];
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalise=v=>String(v||'').replace(/\s+/g,' ').trim();
  function load(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
  function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
  function open(name,focus=false){const found=PAGES.findIndex(x=>x[0]===name);index=found<0?0:found;const key=PAGES[index][0];all('[data-cf360-panel]').forEach(n=>{const a=n.dataset.cf360Panel===key;n.hidden=!a;n.classList.toggle('active',a);});all('[data-cf360-page]').forEach(n=>n.classList.toggle('active',n.dataset.cf360Page===key));one('[data-cf360-counter]').textContent=`Page ${index+1} of 6`;one('[data-cf360-page-title]').textContent=PAGES[index][1];one('[data-cf360-prev]').disabled=index===0;one('[data-cf360-next]').disabled=index===5;renderDots();if(focus)one('.cf360-viewport')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function renderDots(){one('[data-cf360-dots]').innerHTML=PAGES.map((p,i)=>`<button class="${i===index?'active':''}" data-cf360-dot="${p[0]}" type="button" aria-label="Open ${safe(p[1])}"></button>`).join('')}
  function renderManifest(){one('[data-cf360-manifest]').innerHTML=MANIFEST.map((item,i)=>`<article><small>FILE ${String(i+1).padStart(2,'0')}</small><strong>${safe(item.path)}</strong><p>${item.bytes.toLocaleString('en-MY')} bytes</p></article>`).join('')}
  function renderEvidence(){const holder=one('[data-cf360-evidence]');if(!evidence){holder.innerHTML='<article><small>STATUS</small><strong>Evidence not loaded.</strong><p>Run live verification after deployment.</p></article>';return}const rows=[['Release',evidence.release],['Build ID',evidence.build_id],['Commit',evidence.commit_sha],['Workflow run',evidence.workflow_run_id],['Run number',evidence.workflow_run_number],['Deployed at',evidence.deployed_at],['Repository',evidence.repository],['Branch',evidence.branch],['Project',evidence.cloudflare_project],['Domain',evidence.live_domain]];holder.innerHTML=rows.map(r=>`<article><small>${safe(r[0])}</small><strong>${safe(r[1]||'Unavailable')}</strong></article>`).join('');one('[data-cf360-commit]').textContent=evidence.commit_sha||'Unavailable';one('[data-cf360-run]').textContent=evidence.workflow_run_id||'Unavailable';one('[data-cf360-record-commit]').textContent=(evidence.commit_sha||'PENDING').slice(0,12);one('[data-cf360-workflow]').textContent='DEPLOYED';one('[data-cf360-workflow-stamp]').textContent='DEPLOYED';one('[data-cf360-evidence-stamp]').textContent='LOADED'}
  async function loadEvidence(){try{const response=await fetch('/deployment-evidence.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);evidence=await response.json();save(EVIDENCE_KEY,evidence);renderEvidence();return evidence}catch(error){evidence={release:'v1.36.1',build_id:'EKH-OS-COOTP-20260731-001',error:String(error.message||error),loaded_at:new Date().toISOString()};save(EVIDENCE_KEY,evidence);renderEvidence();throw error}}
  function check(id,title,status,detail){return{id,title,status,detail,checked_at:new Date().toISOString()}}
  async function runVerification(){const checks=[];let ev=evidence;try{ev=await loadEvidence();checks.push(check('CF-01','Deployment evidence','PASS','Evidence file loaded.'))}catch(error){checks.push(check('CF-01','Deployment evidence','FAIL',String(error.message||error)))}try{const r=await fetch('/',{cache:'no-store'});const t=await r.text();checks.push(check('CF-02','Live document',r.ok&&t.includes('EKH-OS-COOTP-20260731-001')?'PASS':'FAIL',`HTTP ${r.status}`));const expected={'content-security-policy':'Content Security Policy','x-content-type-options':'Content type protection','referrer-policy':'Referrer policy','permissions-policy':'Permissions policy','cross-origin-opener-policy':'Opener policy','cross-origin-resource-policy':'Resource policy'};for(const [header,title] of Object.entries(expected)){checks.push(check(`HDR-${header}`,title,r.headers.get(header)?'PASS':'FAIL',r.headers.get(header)||'Header missing.'))}}catch(error){checks.push(check('CF-02','Live document','FAIL',String(error.message||error)))}for(const file of ['assets/css/ekh-os.v1.36.1.css','assets/js/ekh-os-core.v1.36.1.js','ekh-os-config.js']){try{const r=await fetch('/'+file,{cache:'no-store'});checks.push(check('ASSET-'+file,file,r.ok?'PASS':'FAIL',`HTTP ${r.status}`))}catch(error){checks.push(check('ASSET-'+file,file,'FAIL',String(error.message||error)))}}const passed=checks.every(c=>c.status==='PASS');evidence={...(ev||{}),verification:checks,verified_at:new Date().toISOString(),live_status:passed?'PASS':'FAIL'};save(EVIDENCE_KEY,evidence);renderChecks();renderEvidence();one('[data-cf360-live]').textContent=passed?'PASS':'FAIL';one('[data-cf360-live-stamp]').textContent=passed?'PASS':'FAIL';one('[data-cf360-record-live]').textContent=passed?'PASS':'FAIL';open('verification',true)}
  function renderChecks(){const checks=evidence?.verification||[];one('[data-cf360-checks]').innerHTML=checks.length?checks.map(c=>`<article class="${c.status.toLowerCase()}"><small>${safe(c.id)}</small><strong>${safe(c.title)} · ${safe(c.status)}</strong><p>${safe(c.detail)}</p></article>`).join(''):'<article class="blocked"><small>STATUS</small><strong>Verification not run.</strong><p>Run checks after deployment.</p></article>'}
  function signature(name){const p=one('[data-cf360-signature-preview]');const n=normalise(name);p.textContent=n||'Owner signature';p.classList.toggle('sig243-placeholder',!n)}
  function loadRecord(){const r=load(RECORD_KEY);if(!r)return;all('input[name="cf360Decision"]').forEach(i=>i.checked=i.value===r.decision);one('[data-cf360-note]').value=r.note||'';all('[data-cf360-confirm]').forEach(i=>i.checked=!!r.confirmations?.[i.dataset.cf360Confirm]);one('[data-cf360-sign-name]').value=r.signer||'';signature(r.signer||'');one('[data-cf360-sign-time]').textContent=new Date(r.signed_at).toLocaleString('en-MY');one('[data-cf360-record-status]').textContent=r.decision.replaceAll('_',' ');one('[data-cf360-record-output]').innerHTML=`<span class="section-kicker">CURRENT LOCAL RECORD</span><strong>${safe(r.decision.replaceAll('_',' '))} · ${safe(r.signer)}</strong><p>${safe(new Date(r.signed_at).toLocaleString('en-MY'))}</p>`}
  function record(){const decision=one('input[name="cf360Decision"]:checked')?.value||'';const signer=normalise(one('[data-cf360-sign-name]').value);const confirmations={};all('[data-cf360-confirm]').forEach(i=>confirmations[i.dataset.cf360Confirm]=i.checked);const problems=[];if(!decision)problems.push('Select a deployment decision.');if(!signer)problems.push('Type the owner name.');if(!Object.values(confirmations).every(Boolean))problems.push('Complete all confirmations.');if(problems.length){one('[data-cf360-error]').textContent=problems.join(' ');return}const r={release:'v1.36.1',build_id:'EKH-OS-COOTP-20260731-001',decision,note:normalise(one('[data-cf360-note]').value),signer,confirmations,evidence:evidence||null,signed_at:new Date().toISOString(),production_write:false};save(RECORD_KEY,r);one('[data-cf360-error]').textContent='';loadRecord()}
  function exportJson(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
  page.addEventListener('click',e=>{const tab=e.target.closest('[data-cf360-page]');if(tab)open(tab.dataset.cf360Page,true);const jump=e.target.closest('[data-cf360-open]');if(jump)open(jump.dataset.cf360Open,true);const dot=e.target.closest('[data-cf360-dot]');if(dot)open(dot.dataset.cf360Dot,true)});one('[data-cf360-prev]').onclick=()=>open(PAGES[Math.max(0,index-1)][0],true);one('[data-cf360-next]').onclick=()=>open(PAGES[Math.min(5,index+1)][0],true);one('[data-cf360-load-evidence]').onclick=()=>loadEvidence().catch(()=>{});one('[data-cf360-run]').onclick=runVerification;one('[data-cf360-clear]').onclick=()=>{localStorage.removeItem(EVIDENCE_KEY);evidence=null;renderEvidence();renderChecks()};one('[data-cf360-export-evidence]').onclick=()=>exportJson(evidence||{status:'NOT_LOADED'},'EKH_OS_Deployment_Evidence.json');one('[data-cf360-sign-name]').oninput=e=>signature(e.target.value);one('[data-cf360-record]').onclick=record;one('[data-cf360-reset]').onclick=()=>{localStorage.removeItem(RECORD_KEY);location.reload()};one('[data-cf360-export-record]').onclick=()=>exportJson(load(RECORD_KEY)||{status:'NOT_RECORDED'},'EKH_OS_Deployment_Record.json');const v=one('.cf360-viewport');v.addEventListener('touchstart',e=>startX=e.changedTouches[0]?.clientX??null,{passive:true});v.addEventListener('touchend',e=>{if(startX===null)return;const d=(e.changedTouches[0]?.clientX??startX)-startX;startX=null;if(Math.abs(d)>52)open(PAGES[Math.max(0,Math.min(5,index+(d<0?1:-1)))][0],true)},{passive:true});renderManifest();renderEvidence();renderChecks();loadRecord();open('brief');
})();
