
(() => {
  'use strict';
  const CHECKS = [{"id": "RT-01", "group": "Connection", "title": "Public configuration", "method": "Validate project URL and publishable key.", "write": false}, {"id": "RT-02", "group": "Connection", "title": "Supabase client library", "method": "Confirm browser client availability.", "write": false}, {"id": "RT-03", "group": "Session", "title": "Authenticated session", "method": "Read the persisted session.", "write": false}, {"id": "RT-04", "group": "Session", "title": "Verified user identity", "method": "Revalidate the current user.", "write": false}, {"id": "RT-05", "group": "Role", "title": "Active staff profile", "method": "Read the authenticated profile.", "write": false}, {"id": "RT-06", "group": "Role", "title": "File access grants", "method": "Read current user grants.", "write": false}, {"id": "RT-07", "group": "Data", "title": "Staff directory access", "method": "Read active staff folders.", "write": false}, {"id": "RT-08", "group": "Data", "title": "Activities RLS access", "method": "Count owner activity records.", "write": false}, {"id": "RT-09", "group": "Storage", "title": "Personal folder access", "method": "List the personal storage folder.", "write": false}];
  const PAGES = [['brief','Runtime Brief'],['session','Session & Identity'],['role','Profile & Grants'],['data','Data Access'],['storage','Storage & RLS'],['decision','Runtime Decision']];
  const EVIDENCE_KEY = 'ekh_rt330_runtime_evidence_v1330';
  const DECISION_KEY = 'ekh_rt330_runtime_decision_v1330';
  const page = document.getElementById('authenticated-runtime');
  if(!page) return;
  if(typeof pageNames !== 'undefined') pageNames['authenticated-runtime'] = ['Authenticated Runtime','System / Supabase Evidence'];

  let pageIndex = 0;
  let touchStartX = null;
  let running = false;
  let authEvent = 'NOT OBSERVED';
  let evidence = loadEvidence() || createEvidence();
  const one = selector => page.querySelector(selector);
  const all = selector => [...page.querySelectorAll(selector)];
  const safe = value => String(value ?? '').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const normalise = value => String(value || '').replace(/\s+/g,' ').trim();
  const nowIso = () => new Date().toISOString();

  function createEvidence(){
    return {release:'v1.33.0',build_id:'EKH-OS-ASRD-20260731-001',runtime:'authenticated-supabase',run_id:null,started_at:null,completed_at:null,mode:'not-run',user:null,profile:null,grants:[],checks:CHECKS.map(item=>({...item,status:'BLOCKED',detail:'Authenticated evidence pending.',latency_ms:null,checked_at:null,error_code:null})),limits:['No production writes.','No access tokens exported.','Cross-role isolation remains untested.']};
  }
  function loadEvidence(){try{return JSON.parse(localStorage.getItem(EVIDENCE_KEY)||'null')}catch{return null}}
  function saveEvidence(){localStorage.setItem(EVIDENCE_KEY,JSON.stringify(evidence))}
  function state(){return window.EKH_AUTH?.getState?.() || {authorised:false,user:null,profile:null}}
  function client(){return window.ekhSupabase || null}
  function elapsed(start){return Math.max(0,Math.round(performance.now()-start))}
  function result(id,status,detail,latency=null,errorCode=null,extra={}){
    const index=evidence.checks.findIndex(item=>item.id===id);
    const base={...(index>=0?evidence.checks[index]:CHECKS.find(item=>item.id===id)),status,detail,latency_ms:latency,checked_at:nowIso(),error_code:errorCode,...extra};
    if(index>=0)evidence.checks[index]=base;else evidence.checks.push(base);
    renderCheck(base);saveEvidence();return base;
  }
  function blocked(id,detail){return result(id,'BLOCKED',detail,null,null)}
  function renderCheck(check){
    const row=one(`[data-rt330-check="${check.id}"]`);if(!row)return;
    row.classList.remove('pass','conditional','fail','blocked');row.classList.add(check.status.toLowerCase());
    row.querySelector('[data-rt330-check-status]').textContent=check.status;
    row.querySelector('[data-rt330-check-latency]').textContent=Number.isFinite(check.latency_ms)?`${check.latency_ms} ms`:'—';
    const paragraph=row.querySelector('p');if(paragraph)paragraph.textContent=check.detail;
  }
  function counts(){
    const c={PASS:0,CONDITIONAL:0,FAIL:0,BLOCKED:0};evidence.checks.forEach(item=>{c[item.status]=(c[item.status]||0)+1});return c;
  }
  function overallStatus(){const c=counts();if(c.FAIL)return'FAIL';if(c.BLOCKED)return evidence.completed_at?'PARTIAL':'BLOCKED';if(c.CONDITIONAL)return'CONDITIONAL';if(c.PASS===CHECKS.length)return'PASS';return'NOT RUN'}
  function renderSummary(){
    const c=counts(),overall=overallStatus();one('[data-rt330-summary-state]').textContent=overall;one('[data-rt330-summary-detail]').textContent=evidence.completed_at?`Last run ${new Date(evidence.completed_at).toLocaleString('en-MY')}`:'Authenticated evidence pending';one('[data-rt330-summary-pass]').textContent=`${c.PASS}/${CHECKS.length}`;one('[data-rt330-decision-pass]').textContent=`${c.PASS}/${CHECKS.length}`;one('[data-rt330-decision-fail]').textContent=String(c.FAIL);one('[data-rt330-decision-blocked]').textContent=String(c.BLOCKED);one('[data-rt330-data-stamp]').textContent=overall;one('[data-rt330-session-stamp]').textContent=evidence.checks.find(x=>x.id==='RT-03')?.status||'NOT RUN';one('[data-rt330-role-stamp]').textContent=evidence.checks.find(x=>x.id==='RT-05')?.status||'NOT RUN';one('[data-rt330-storage-stamp]').textContent=evidence.checks.find(x=>x.id==='RT-09')?.status||'NOT RUN';
    const user=evidence.user;const profile=evidence.profile;one('[data-rt330-summary-user]').textContent=user?.email||'UNKNOWN';one('[data-rt330-summary-role]').textContent=profile?.app_role||'No verified role';one('[data-rt330-matrix-session]').textContent=evidence.checks.find(x=>x.id==='RT-03')?.status||'NOT RUN';one('[data-rt330-matrix-folder]').textContent=evidence.checks.find(x=>x.id==='RT-09')?.status||'NOT RUN';const tableStatuses=['RT-05','RT-06','RT-07','RT-08'].map(id=>evidence.checks.find(x=>x.id===id)?.status);one('[data-rt330-matrix-tables]').textContent=tableStatuses.includes('FAIL')?'FAIL':tableStatuses.every(x=>x==='PASS')?'PASS':tableStatuses.includes('BLOCKED')?'BLOCKED':'CONDITIONAL';
  }
  function renderIdentity(){
    const user=evidence.user||{},profile=evidence.profile||{};const session=evidence.session||{};
    one('[data-rt330-fact-authorised]').textContent=state().authorised?'YES':'NO';one('[data-rt330-fact-email]').textContent=user.email||'UNKNOWN';one('[data-rt330-fact-user-id]').textContent=user.id||'UNKNOWN';one('[data-rt330-fact-expiry]').textContent=session.expires_at?new Date(session.expires_at*1000).toLocaleString('en-MY'):'UNKNOWN';one('[data-rt330-fact-auth-event]').textContent=authEvent;one('[data-rt330-fact-run]').textContent=evidence.completed_at?new Date(evidence.completed_at).toLocaleString('en-MY'):'NOT RUN';
    one('[data-rt330-profile-name]').textContent=profile.display_name||'UNKNOWN';one('[data-rt330-profile-role]').textContent=profile.app_role||'UNKNOWN';one('[data-rt330-profile-slug]').textContent=profile.staff_slug||'UNKNOWN';one('[data-rt330-profile-department]').textContent=profile.department||'UNKNOWN';one('[data-rt330-profile-team]').textContent=profile.team_code||'UNKNOWN';one('[data-rt330-profile-source]').textContent=profile.bootstrap_fallback?'OWNER FALLBACK':profile.user_id?'SUPABASE PROFILE':'UNKNOWN';
    one('[data-rt330-grant-count]').textContent=`${evidence.grants?.length||0} grants`;const holder=one('[data-rt330-grant-list]');holder.innerHTML=(evidence.grants||[]).map(grant=>`<div class="rt330-grant-row"><span>${safe(grant.staff_slug)}</span><b>${safe(grant.access_level)}</b></div>`).join('')||'<p>No explicit grants returned.</p>';
  }
  function renderMessage(title,detail,mode=''){const box=one('[data-rt330-runtime-message]');box.className=`rt330-runtime-message ${mode}`;box.querySelector('strong').textContent=title;box.querySelector('p').textContent=detail}
  function renderAll(){evidence.checks.forEach(renderCheck);renderSummary();renderIdentity();renderReview(loadDecision())}
  function publicConfig(){let saved={};try{saved=JSON.parse(localStorage.getItem('ekh_os_v13_supabase_config')||'{}')}catch{}const injected=window.EKH_OS_PUBLIC_CONFIG||{};return{url:injected.url||saved.url||'',key:injected.key||saved.key||''}}
  function validConfig(config){return /^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(config.url||'')&&Boolean(config.key)&&!/^sb_secret_/i.test(config.key)&&!/service[_-]?role/i.test(config.key)}
  async function timed(fn){const start=performance.now();try{const value=await fn();return{ok:true,value,latency:elapsed(start)}}catch(error){return{ok:false,error,latency:elapsed(start)}}}
  async function runChecks(){
    if(running)return;running=true;all('[data-rt330-run]').forEach(button=>button.disabled=true);renderMessage('Runtime checks are running.','Read-only requests are executing.');
    evidence=createEvidence();evidence.run_id=globalThis.crypto?.randomUUID?.()||`rt-${Date.now()}`;evidence.started_at=nowIso();
    const config=publicConfig();result('RT-01',validConfig(config)?'PASS':'FAIL',validConfig(config)?'Public browser configuration is valid.':'Public configuration is invalid.',0,validConfig(config)?null:'INVALID_PUBLIC_CONFIG',{project_url:config.url||null,key_type:config.key?.startsWith('sb_publishable_')?'publishable':config.key?'anon-or-legacy':'missing'});
    const supabaseReady=Boolean(window.supabase?.createClient);result('RT-02',supabaseReady?'PASS':'FAIL',supabaseReady?'Supabase client library loaded.':'Supabase client library missing.',0,supabaseReady?null:'CLIENT_LIBRARY_MISSING');
    const authState=state();if(authState.preview){CHECKS.slice(2).forEach(item=>blocked(item.id,'Preview mode blocks authentication.'));evidence.mode='preview';evidence.completed_at=nowIso();saveEvidence();renderMessage('Preview mode blocks runtime.','Use the full authenticated build.','blocked');running=false;all('[data-rt330-run]').forEach(button=>button.disabled=false);renderAll();return}
    const sb=client();if(!sb){CHECKS.slice(2).forEach(item=>blocked(item.id,'Supabase client is unavailable.'));evidence.mode='blocked';evidence.completed_at=nowIso();saveEvidence();renderMessage('Supabase client is unavailable.','Sign in through the secure gate.','blocked');running=false;all('[data-rt330-run]').forEach(button=>button.disabled=false);renderAll();return}
    const sessionResult=await timed(()=>sb.auth.getSession());const session=sessionResult.value?.data?.session||null;if(!sessionResult.ok||sessionResult.value?.error||!session){result('RT-03','FAIL',sessionResult.value?.error?.message||sessionResult.error?.message||'No authenticated session exists.',sessionResult.latency,'SESSION_MISSING');CHECKS.slice(3).forEach(item=>blocked(item.id,'Authenticated session required.'));evidence.mode='unauthenticated';evidence.completed_at=nowIso();saveEvidence();renderMessage('Authenticated session is missing.','Sign in before running checks.','fail');running=false;all('[data-rt330-run]').forEach(button=>button.disabled=false);renderAll();return}
    evidence.session={expires_at:session.expires_at,token_type:session.token_type};result('RT-03','PASS','Authenticated session is current.',sessionResult.latency,null,{expires_at:session.expires_at});
    const userResult=await timed(()=>sb.auth.getUser());const user=userResult.value?.data?.user||null;if(!userResult.ok||userResult.value?.error||!user){result('RT-04','FAIL',userResult.value?.error?.message||userResult.error?.message||'User identity failed.',userResult.latency,'USER_REVALIDATION_FAILED');CHECKS.slice(4).forEach(item=>blocked(item.id,'Verified identity required.'));evidence.mode='identity-failed';evidence.completed_at=nowIso();saveEvidence();renderMessage('User identity failed.','Sign in again.','fail');running=false;all('[data-rt330-run]').forEach(button=>button.disabled=false);renderAll();return}
    evidence.user={id:user.id,email:user.email||null,created_at:user.created_at||null,last_sign_in_at:user.last_sign_in_at||null};result('RT-04','PASS','Current user identity is verified.',userResult.latency);
    const appProfile=authState.profile||null;const profileResult=await timed(()=>sb.from('ekh_staff_profiles').select('user_id,staff_slug,display_name,department,job_title,app_role,team_code,is_active').eq('user_id',user.id).maybeSingle());const profileRow=profileResult.value?.data||null;const profileError=profileResult.value?.error||profileResult.error||null;const activeProfile=profileRow?.is_active?profileRow:appProfile;
    if(profileRow?.is_active){evidence.profile=profileRow;result('RT-05','PASS','Active Supabase profile is readable.',profileResult.latency)}else if(appProfile?.bootstrap_fallback){evidence.profile=appProfile;result('RT-05','CONDITIONAL','Owner fallback profile is active.',profileResult.latency,profileError?.code||'OWNER_FALLBACK')}else{evidence.profile=appProfile;result('RT-05','FAIL',profileError?.message||'Active staff profile is unavailable.',profileResult.latency,profileError?.code||'PROFILE_UNAVAILABLE')}
    const grantsResult=await timed(()=>sb.from('ekh_staff_file_access').select('staff_slug,access_level').eq('user_id',user.id));const grantsError=grantsResult.value?.error||grantsResult.error||null;if(grantsError){evidence.grants=[];result('RT-06','FAIL',grantsError.message||'Access grants failed.',grantsResult.latency,grantsError.code||'GRANTS_UNAVAILABLE')}else{evidence.grants=grantsResult.value?.data||[];const ownerOverride=['owner','admin'].includes(activeProfile?.app_role);result('RT-06','PASS',ownerOverride?'Owner role grants wildcard access.':`${evidence.grants.length} explicit grants returned.`,grantsResult.latency,null,{grant_count:evidence.grants.length,owner_override:ownerOverride})}
    const foldersResult=await timed(()=>sb.from('ekh_staff_folders').select('staff_slug,is_active',{count:'exact'}).eq('is_active',true));const foldersError=foldersResult.value?.error||foldersResult.error||null;if(foldersError){result('RT-07','FAIL',foldersError.message||'Staff directory failed.',foldersResult.latency,foldersError.code||'DIRECTORY_UNAVAILABLE')}else{const count=foldersResult.value?.count??foldersResult.value?.data?.length??0;result('RT-07',count>=35?'PASS':'CONDITIONAL',`${count} active folders returned.`,foldersResult.latency,null,{active_folder_count:count})}
    const activitiesResult=await timed(()=>sb.from('ekh_activities').select('id',{count:'exact',head:true}).eq('owner_id',user.id));const activitiesError=activitiesResult.value?.error||activitiesResult.error||null;if(activitiesError){result('RT-08','FAIL',activitiesError.message||'Activities RLS failed.',activitiesResult.latency,activitiesError.code||'ACTIVITIES_UNAVAILABLE')}else{result('RT-08','PASS',`${activitiesResult.value?.count??0} owner activities are visible.`,activitiesResult.latency,null,{visible_activity_count:activitiesResult.value?.count??0})}
    const slug=activeProfile?.staff_slug||appProfile?.staff_slug||null;if(!slug){blocked('RT-09','A staff slug is required.')}else{const storageResult=await timed(()=>sb.storage.from('ekh-staff-files').list(`staff/${slug}`,{limit:1,sortBy:{column:'updated_at',order:'desc'}}));const storageError=storageResult.value?.error||storageResult.error||null;if(storageError){result('RT-09','FAIL',storageError.message||'Personal storage failed.',storageResult.latency,storageError.statusCode||storageError.name||'STORAGE_UNAVAILABLE')}else{result('RT-09','PASS','Personal folder listing succeeded.',storageResult.latency,null,{staff_slug:slug,returned_items:storageResult.value?.data?.length||0})}}
    evidence.mode='authenticated-read-only';evidence.completed_at=nowIso();saveEvidence();const c=counts();const status=overallStatus();renderMessage(status==='PASS'?'Authenticated reads passed.':status==='FAIL'?'Runtime checks found failures.':'Runtime evidence remains partial.',`${c.PASS} passed. ${c.FAIL} failed. ${c.BLOCKED} blocked.`,status.toLowerCase());running=false;all('[data-rt330-run]').forEach(button=>button.disabled=false);renderAll();
  }
  async function refreshAccess(){const stateBefore=state();if(stateBefore.preview){renderMessage('Preview mode blocks refresh.','Use the full authenticated build.','blocked');return}if(!stateBefore.authorised){renderMessage('Authentication is required.','Sign in through the secure gate.','blocked');return}renderMessage('Refreshing authenticated access.','Role validation is running.');try{await window.EKH_AUTH?.refreshAccess?.();setTimeout(runChecks,400)}catch(error){renderMessage('Access refresh failed.',error.message||'Unknown refresh error.','fail')}}
  function openPage(name,{focus=false}={}){const index=PAGES.findIndex(item=>item[0]===name);pageIndex=index>=0?index:0;const[key,title]=PAGES[pageIndex];all('[data-rt330-panel]').forEach(panel=>{const active=panel.dataset.rt330Panel===key;panel.hidden=!active;panel.classList.toggle('active',active);panel.setAttribute('aria-hidden',String(!active))});all('[data-rt330-page]').forEach(button=>{const active=button.dataset.rt330Page===key;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))});one('[data-rt330-counter]').textContent=`Page ${pageIndex+1} of ${PAGES.length}`;one('[data-rt330-page-title]').textContent=title;one('[data-rt330-prev]').disabled=pageIndex===0;one('[data-rt330-next]').disabled=pageIndex===PAGES.length-1;renderDots();if(focus)one('.rt330-viewport')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
  function move(delta){const next=Math.max(0,Math.min(PAGES.length-1,pageIndex+delta));openPage(PAGES[next][0],{focus:true})}
  function renderDots(){one('[data-rt330-dots]').innerHTML=PAGES.map((item,index)=>`<button class="${index===pageIndex?'active':''}" data-rt330-dot="${item[0]}" type="button" aria-label="Open ${safe(item[1])}"></button>`).join('')}
  function loadDecision(){try{return JSON.parse(localStorage.getItem(DECISION_KEY)||'null')}catch{return null}}
  function renderSignature(name){const preview=one('[data-rt330-signature-preview]');const clean=normalise(name);preview.textContent=clean||'Owner signature';preview.classList.toggle('sig243-placeholder',!clean)}
  function renderReview(record){const holder=one('[data-rt330-record-output]');holder.classList.remove('approved','returned','hold');if(!record){holder.innerHTML='<span class="section-kicker">CURRENT LOCAL RECORD</span><strong>No runtime decision exists.</strong><p>Run, review, then sign.</p>';one('[data-rt330-summary-decision]').textContent='PENDING';return}const className=record.decision==='AUTHENTICATED_READS_PASS'?'approved':record.decision==='HOLD'?'hold':'returned';holder.classList.add(className);holder.innerHTML=`<span class="section-kicker">CURRENT LOCAL RECORD</span><strong>${safe(record.decision.replaceAll('_',' '))} · ${safe(record.signer)}</strong><p>${safe(new Date(record.signed_at).toLocaleString('en-MY'))}${record.note?` · ${safe(record.note)}`:''}</p>`;one('[data-rt330-summary-decision]').textContent=record.decision.replaceAll('_',' ')}
  function loadReview(){const record=loadDecision();all('input[name="rt330Decision"]').forEach(input=>input.checked=Boolean(record&&input.value===record.decision));one('[data-rt330-decision-note]').value=record?.note||'';all('[data-rt330-confirm]').forEach(input=>input.checked=Boolean(record?.confirmations?.[input.dataset.rt330Confirm]));one('[data-rt330-sign-name]').value=record?.signer||'';renderSignature(record?.signer||'');one('[data-rt330-sign-time]').textContent=record?.signed_at?new Date(record.signed_at).toLocaleString('en-MY'):'Not signed';renderReview(record)}
  function recordReview(){const decision=one('input[name="rt330Decision"]:checked')?.value||'';const signer=normalise(one('[data-rt330-sign-name]').value);const note=normalise(one('[data-rt330-decision-note]').value);const confirmations={};all('[data-rt330-confirm]').forEach(input=>confirmations[input.dataset.rt330Confirm]=input.checked);const problems=[];if(!decision)problems.push('Select a runtime decision.');if(!signer)problems.push('Type the owner name.');if(!Object.values(confirmations).every(Boolean))problems.push('Complete all confirmations.');const error=one('[data-rt330-error]');if(problems.length){error.textContent=problems.join(' ');return}error.textContent='';const record={release:'v1.33.0',build_id:'EKH-OS-ASRD-20260731-001',decision,note,signer,confirmations,evidence_run_id:evidence.run_id,evidence_status:overallStatus(),evidence_counts:counts(),signed_at:nowIso(),storage:'local-browser-draft',supabase_write:false,production_write:false};localStorage.setItem(DECISION_KEY,JSON.stringify(record));loadReview()}
  function clearReview(){localStorage.removeItem(DECISION_KEY);all('input[name="rt330Decision"]').forEach(input=>input.checked=false);one('[data-rt330-decision-note]').value='';all('[data-rt330-confirm]').forEach(input=>input.checked=false);one('[data-rt330-sign-name]').value='';renderSignature('');one('[data-rt330-sign-time]').textContent='Not signed';renderReview(null)}
  function exportEvidence(){const record={release:'v1.33.0',build_id:'EKH-OS-ASRD-20260731-001',exported_at:nowIso(),evidence,decision:loadDecision(),security:{access_tokens_exported:false,refresh_tokens_exported:false,passwords_exported:false},writes:{database:0,storage:0,rpc:0,production:0}};const blob=new Blob([JSON.stringify(record,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`EKH_OS_Authenticated_Runtime_${new Date().toISOString().replaceAll(':','-')}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0)}

  page.addEventListener('click',event=>{const tab=event.target.closest('[data-rt330-page]');if(tab)openPage(tab.dataset.rt330Page,{focus:true});const jump=event.target.closest('[data-rt330-open-page]');if(jump)openPage(jump.dataset.rt330OpenPage,{focus:true});const dot=event.target.closest('[data-rt330-dot]');if(dot)openPage(dot.dataset.rt330Dot,{focus:true})});
  all('[data-rt330-run]').forEach(button=>button.addEventListener('click',runChecks));all('[data-rt330-refresh]').forEach(button=>button.addEventListener('click',refreshAccess));one('[data-rt330-prev]').addEventListener('click',()=>move(-1));one('[data-rt330-next]').addEventListener('click',()=>move(1));one('[data-rt330-sign-name]').addEventListener('input',event=>renderSignature(event.target.value));one('[data-rt330-record]').addEventListener('click',recordReview);one('[data-rt330-clear]').addEventListener('click',clearReview);one('[data-rt330-export]').addEventListener('click',exportEvidence);
  const viewport=one('.rt330-viewport');viewport.addEventListener('touchstart',event=>{touchStartX=event.changedTouches[0]?.clientX??null},{passive:true});viewport.addEventListener('touchend',event=>{if(touchStartX===null)return;const endX=event.changedTouches[0]?.clientX??touchStartX;const distance=endX-touchStartX;touchStartX=null;if(Math.abs(distance)<52)return;move(distance<0?1:-1)},{passive:true});
  document.addEventListener('keydown',event=>{const activeView=document.querySelector('.page-content > .view.active');if(activeView!==page)return;if(event.target.matches('input,textarea,select,[contenteditable="true"]'))return;if(['ArrowRight','PageDown'].includes(event.key)){event.preventDefault();move(1)}if(['ArrowLeft','PageUp'].includes(event.key)){event.preventDefault();move(-1)}if(event.key==='Home'){event.preventDefault();openPage('brief',{focus:true})}if(event.key==='End'){event.preventDefault();openPage('decision',{focus:true})}});
  window.addEventListener('ekh-auth-ready',event=>{authEvent='AUTH READY';evidence.user=event.detail?.user?{id:event.detail.user.id,email:event.detail.user.email||null}:evidence.user;evidence.profile=event.detail?.profile||evidence.profile;renderAll();setTimeout(()=>{if(!evidence.completed_at)runChecks()},500)});
  try{window.ekhSupabase?.auth?.onAuthStateChange?.((event)=>{authEvent=event;one('[data-rt330-fact-auth-event]').textContent=event})}catch{}
  renderAll();loadReview();openPage('brief');if(state().authorised&&!state().preview&&!evidence.completed_at)setTimeout(runChecks,700);
})();
